### ISSUE TITLE
result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by GZHenry** [LuminLiu/HierFL#1]
With Cirfar10
Traceback (most recent call last):
  File "/home/caobokai/codes/HierFL-master/hierfavg.py", line 363, in <module>
    main()
  File "/home/caobokai/codes/HierFL-master/hierfavg.py", line 360, in main
    HierFAVG(args)
  File "/home/caobokai/codes/HierFL-master/hierfavg.py", line 326, in HierFAVG
    edge.aggregate(args)
  File "/home/caobokai/codes/HierFL-master/edge.py", line 63, in aggregate
    self.shared_state_dict = average_weights(w = received_dict,
  File "/home/caobokai/codes/HierFL-master/average.py", line 13, in average_weights
    w_avg[k] += torch.mul(w[i][k], s_num[i]/temp_sample_num)
RuntimeError: result type Float can't be cast to the desired output type Long

**Comment by LuminLiu** [comment]
Hi, the error can be solved by changing:
`w_avg[k] += torch.mul(w[i][k], s_num[i]/temp_sample_num)`
to :
`w_avg[k] = w_avg[k] + torch.mul(w[i][k], s_num[i]/temp_sample_num)`.
It might be the torch version problem.
I will update the code later. Thanks for raising this problem!

**Comment by teixobactin** [comment]
Traceback (most recent call last):
  File "D:/python/HierFL-master/hierfavg.py", line 362, in <module>
    main()
  File "D:/python/HierFL-master/hierfavg.py", line 359, in main
    HierFAVG(args)
  File "D:/python/HierFL-master/hierfavg.py", line 215, in HierFAVG
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_dataloaders(args)
  File "D:\python\HierFL-master\datasets\get_data.py", line 11, in get_dataloaders
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_dataset(dataset_root='data',
  File "D:\python\HierFL-master\datasets\cifar_mnist.py", line 305, in get_dataset
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_cifar10(dataset_root, args)
  File "D:\python\HierFL-master\datasets\cifar_mnist.py", line 362, in get_cifar10
    raise ValueError("this nn for cifar10 not implemented")
ValueError: this nn for cifar10 not implemented
