### ISSUE TITLE
ValueError: this nn for cifar10 not implemented

### ISSUE THREAD

**Issue by teixobactin** [LuminLiu/HierFL#3]
Traceback (most recent call last):
  File "D:/python/HierFL-master/hierfavg.py", line 362, in <module>
    main()
  File "D:/python/HierFL-master/hierfavg.py", line 359, in main
    HierFAVG(args)
  File "D:/python/HierFL-master/hierfavg.py", line 215, in HierFAVG
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_dataloaders(args)
  File "D:\python\HierFL-master\datasets\get_data.py", line 11, in get_dataloaders
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_dataset(dataset_root='data',
  File "D:\python\HierFL-master\datasets\cifar_mnist.py", line 305, in get_dataset
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_cifar10(dataset_root, args)
  File "D:\python\HierFL-master\datasets\cifar_mnist.py", line 362, in get_cifar10
    raise ValueError("this nn for cifar10 not implemented")
ValueError: this nn for cifar10 not implemented

**Comment by gogoingoing** [comment]
+1

**Comment by Bhongcheng** [comment]
![image](https://user-images.githubusercontent.com/90205287/167254327-8cb72f5e-b1a7-4674-ade3-2b0092c16043.png)
It may be caused by the version of Pytorch

**Comment by Bhongcheng** [comment]
You can change the model name which is implemented, such as lenet

**Comment by nsmalotaibi** [comment]
+1

**Comment by nsmalotaibi** [comment]
Any update? please

**Comment by LuminLiu** [comment]
Could you tell me what your input for the args?

**Comment by nsmalotaibi** [comment]
Hi LuminLiu, I just copy and past the command you already wrote in the code as this:
python3 hierfavg.py 
--dataset mnist
--model lenet
--num_clients 50
--num_edges 5
--frac 1
--num_local_update 60
--num_edge_aggregation 1
--num_communication 100
--batch_size 20
--iid 0
--edgeiid 1
--show_dis 1
--lr 0.01
--lr_decay 0.995
--lr_decay_epoch 1
--momentum 0
--weight_decay 0
Using device cpu
Traceback (most recent call last):
  File "/Users/nourasaad/HierFL-master/hierfavg.py", line 362, in <module>
    main()
  File "/Users/nourasaad/HierFL-master/hierfavg.py", line 359, in main
    HierFAVG(args)
  File "/Users/nourasaad/HierFL-master/hierfavg.py", line 215, in HierFAVG
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_dataloaders(args)
  File "/Users/nourasaad/HierFL-master/datasets/get_data.py", line 11, in get_dataloaders
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_dataset(dataset_root='data',
  File "/Users/nourasaad/HierFL-master/datasets/cifar_mnist.py", line 305, in get_dataset
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_cifar10(dataset_root, args)
  File "/Users/nourasaad/HierFL-master/datasets/cifar_mnist.py", line 362, in get_cifar10
    raise ValueError("this nn for cifar10 not implemented")
ValueError: this nn for cifar10 not implemented


zsh: command not found: --dataset

I found that I am working on zsh shell of MAC and I have to add all the arguments in one line which solve the problem for me

**Comment by LuminLiu** [comment]
Hi, I just rechecked, the code is OK. It might be the problem if you copy and paste command lines in README.md. I guess it is the error from the Carriage Return (Line Breaking Symbol) with different coding systems. 
The solution is easy, just type the command by yourself. It should be OK. 
An example would be
`python3 hierfavg.py --dataset mnist --model lenet --num_clients 50 ...`

Thx!
