### ISSUE TITLE
Experimental results

### ISSUE THREAD

**Issue by jiayoudaima** [LuminLiu/HierFL#6]
Hi ，Mr. Liu,
First of all thank you for sharing the source code.
I can't reproduce the results of your experiment. When the number of communication rounds with the cloud is constant, no matter how I adjust the values of k1 and k2, the accuracy is very close, but in your experiment, the values of k1 and k2 are different, and the accuracy is very different.
This issue has been bothering me for a month, I tried various methods to improve it, the effect is not very obvious, eager to get a response from you.

**Comment by jiayoudaima** [comment]
What confuses me even more is that the parameters are set to these ， such as: --dataset mnist,--model lenet,--num_communication 20,--num_local_update 15,--num_edge_aggregation 2,--num_clients 15,--num_edges 3 and so on,I only said the parameters that I set myself，the accuracy of my experiments is about 90%.，but in your experiment, 20 rounds of global updates may not reach 70%，I haven't solved this question for a long time, and I'm eager to get your reply.

**Comment by LuminLiu** [comment]
Hi, did you use iid data split?

**Comment by jiayoudaima** [comment]
I have used IID Data Split, but I understand that the program is executed serially, and the client and edge server are not executed in parallel, which does not seem to be very consistent with the pseudocode in the paper. It may be that the code logic I understand is not very correct, I hope you can help me understand it.




�0�1�1�7
***@***.***







                       
Original Email
                       
                     

Sender:"LuminLiu"< ***@***.*** &gt;;

Sent Time:2023/4/9 15:19

To:"LuminLiu/HierFL"< ***@***.*** &gt;;

Cc recipient:"jiayoudaima"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [LuminLiu/HierFL] Experimental results (Issue #6)




 
Hi, did you use iid data split?

**Comment by jiayoudaima** [comment]
I have used IID Data Split, but I understand that the program is executed serially, and the client and edge server are not executed in parallel, which does not seem to be very consistent with the pseudocode in the paper. It may be that the code logic I understand is not very correct, I hope you can help me understand it.

**Comment by jiayoudaima** [comment]
I have used IID Data Split, but I understand that the program is executed serially, and the client and edge server are not executed in parallel, which does not seem to be very consistent with the pseudocode in the paper. It may be that the code logic I understand is not very correct, I hope you can help me understand it.Thank you so much

**Comment by LuminLiu** [comment]
1. To observe an accuracy loss, you need to change to non-iid setting.
2. Yes, the codes are executed sequentially instead of in parallel, but the simulation performance (accuracy) is unaffected though. Thus, the CPU/GPU runtime is not the training time of an actual FL system. If you want to calculate the FL training time, you need to assume the communication and computation delays and then calculate it with hand.

**Comment by jiayoudaima** [comment]
![Alt text](https://github.com/hzhnb/unity/blob/main/04e78ce9ea3b401c167872e494f4951.png)

**Comment by jiayoudaima** [comment]
Hi ，Mr. Liu,
Thank you very much for your answer.
Regarding the manual calculation of time and energy consumption, can I use the conclusions given in Table 1 in your paper? How to calculate time and energy consumption, can you give me an example?Thank you very much.

**Comment by jiayoudaima** [comment]
![Alt text](https://github.com/jiayoudaima/c/blob/main/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-04-16%20093552.png)

**Comment by jiayoudaima** [comment]
There is always a difference between the time and energy expenditure I have calculated and the calculation time you have given, maybe I have calculated it incorrectly, I would appreciate your help.

**Comment by jiayoudaima** [comment]
Hi ，Mr. Liu,
Thank you very much for your answer.
Can you give me a formula for calculating the total energy expenditure and time to help me reproduce the experiment better, thank you very much.

**Comment by jiayoudaima** [comment]
Hi ，Mr. Liu,
The main parameters I use are: --dataset cifar10 --iid -2 ----edgeiid 1,I get an error like the following, eager to get your help.

Traceback (most recent call last):
  File "D:/Program Files/JetBrains/daima---lianxi/Cloud And Edge(internet and vehicle)/main.py", line 318, in <module>
    HierFAVG(args)
  File "D:/Program Files/JetBrains/daima---lianxi/Cloud And Edge(internet and vehicle)/main.py", line 192, in HierFAVG
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_dataloaders(args)
  File "D:\Program Files\JetBrains\daima---lianxi\Cloud And Edge(internet and vehicle)\dataset\get_data.py", line 301, in get_dataloaders
    test_loaders = split_data(test, args, kwargs, is_shuffle=False)
  File "D:\Program Files\JetBrains\daima---lianxi\Cloud And Edge(internet and vehicle)\dataset\get_data.py", line 284, in split_data
    data_loaders = niid_esize_split_oneclass(dataset, args, kwargs, is_shuffle)
  File "D:\Program Files\JetBrains\daima---lianxi\Cloud And Edge(internet and vehicle)\dataset\get_data.py", line 256, in niid_esize_split_oneclass
    idxs_labels = np.vstack((idxs, labels))
  File "<__array_function__ internals>", line 6, in vstack
  File "D:\anaconda\envs\ren1\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 4 dimension(s)

**Comment by jiayoudaima** [comment]
Hi ，Mr. Liu,
The main parameters I use are: --dataset cifar10 --iid -2 --edgeiid 1,I get an error like the following, eager to get your help.Thank you so much.

Traceback (most recent call last):
File "D:/Program Files/JetBrains/daima---lianxi/Cloud And Edge(internet and vehicle)/main.py", line 318, in
HierFAVG(args)
File "D:/Program Files/JetBrains/daima---lianxi/Cloud And Edge(internet and vehicle)/main.py", line 192, in HierFAVG
train_loaders, test_loaders, v_train_loader, v_test_loader = get_dataloaders(args)
File "D:\Program Files\JetBrains\daima---lianxi\Cloud And Edge(internet and vehicle)\dataset\get_data.py", line 301, in get_dataloaders
test_loaders = split_data(test, args, kwargs, is_shuffle=False)
File "D:\Program Files\JetBrains\daima---lianxi\Cloud And Edge(internet and vehicle)\dataset\get_data.py", line 284, in split_data
data_loaders = niid_esize_split_oneclass(dataset, args, kwargs, is_shuffle)
File "D:\Program Files\JetBrains\daima---lianxi\Cloud And Edge(internet and vehicle)\dataset\get_data.py", line 256, in niid_esize_split_oneclass
idxs_labels = np.vstack((idxs, labels))
File "<array_function internals>", line 6, in vstack
File "D:\anaconda\envs\ren1\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
return _nx.concatenate(arrs, 0)
File "<array_function internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 4 dimension(s)

**Comment by jiayoudaima** [comment]
The main parameter I used is: --dataset cifar10 --iid -2 --edgeiid 1,I get an error like the following,but I don't get the following error in the mnist dataset, eager to get your help.Thank you so much.

Traceback (most recent call last):
  File "D:/Program Files/JetBrains/daima---lianxi/Cloud And Edge(internet and vehicle)/main.py", line 318, in <module>
    HierFAVG(args)
  File "D:/Program Files/JetBrains/daima---lianxi/Cloud And Edge(internet and vehicle)/main.py", line 192, in HierFAVG
    train_loaders, test_loaders, v_train_loader, v_test_loader = get_dataloaders(args)
  File "D:\Program Files\JetBrains\daima---lianxi\Cloud And Edge(internet and vehicle)\dataset\get_data.py", line 301, in get_dataloaders
    test_loaders = split_data(test, args, kwargs, is_shuffle=False)
  File "D:\Program Files\JetBrains\daima---lianxi\Cloud And Edge(internet and vehicle)\dataset\get_data.py", line 284, in split_data
    data_loaders = niid_esize_split_oneclass(dataset, args, kwargs, is_shuffle)
  File "D:\Program Files\JetBrains\daima---lianxi\Cloud And Edge(internet and vehicle)\dataset\get_data.py", line 256, in niid_esize_split_oneclass
    idxs_labels = np.vstack((idxs, labels))
  File "<__array_function__ internals>", line 6, in vstack
  File "D:\anaconda\envs\ren1\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 4 dimension(s)

**Comment by 17600-w** [comment]
Hi ，Mr. Liu,
I'm sorry to bother you. May I ask why I was unsuccessful in using your project cifar10? The following error occurred: Process finished with exit code 137 (interrupted by signal 9: SIGKILL), but mnist was successful. Is this related to my CPU environment
